name: Build Debian Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up package directory
        run: |
          mkdir -p package/usr/local/bin
          mkdir -p package/DEBIAN
          cp hello.sh package/usr/local/bin/hello
          chmod 755 package/usr/local/bin/hello
          cp debian/control package/DEBIAN/control

      - name: Build .deb package
        run: dpkg-deb --build package hello-deb_1.0_all.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello-deb
          path: hello-deb_1.0_all.deb
